tbl = {
	[50824] = {
		unidentifiedDisplayName = "Manto",
		unidentifiedResourceName = "후드",
		identifiedDisplayName = "Manto de Lluvia",
		identifiedResourceName = "발키리의망토",
		identifiedDescriptionName = {
			"Prenda irrompible.",
			"",
			"Evita el Poison aplicado por el clima",
			"de lluvia; no protege de otras fuentes.",
			"",
			"Magos, Arqueros y Acólitos: esquiva perfecta +5,",
			"+2 por refinamiento (máximo +25).",
			"Espadachines, Mercantes y Ladrones: devuelve",
			"daño cuerpo a cuerpo +5%, +2% por refinamiento",
			"(máximo +25%).",
			"",
			"Defensa y bonificaciones según la era.",
			"Peso: 50",
			"Ranura: 1",
		},
		slotCount = 1,
		ClassNum = 0,
	},
	[50825] = {
		unidentifiedDisplayName = "Garment",
		unidentifiedResourceName = "우든메일",
		identifiedDisplayName = "Armadura Horno",
		identifiedResourceName = "불의갑옷",
		identifiedDescriptionName = {
			"Protege del Freeze causado por la Ventisca.",
			"",
			"Resistencia al elemento Fuego.",
			"Defensa: 25 (Renewal) / 4 (Pre-Renewal)",
			"Peso: 220",
			"Ubicación: Garment",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50826] = {
		unidentifiedDisplayName = "Glasses",
		unidentifiedResourceName = "글래스",
		identifiedDisplayName = "Gafas de Claridad",
		identifiedResourceName = "도끼눈",
		identifiedDescriptionName = {
			"Protegen de Blind causado por la Neblina densa.",
			"",
			"Defensa: 2 (Renewal) / 1 (Pre-Renewal)",
			"Peso: 10",
			"Ubicación: Middle Head",
		},
		slotCount = 0,
		ClassNum = 63,
	},
	[50827] = {
		unidentifiedDisplayName = "Gas Mask",
		unidentifiedResourceName = "마스크",
		identifiedDisplayName = "Máscara de Gas Etéreo",
		identifiedResourceName = "가스마스크",
		identifiedDescriptionName = {
			"Protege del Stun causado por Vapores asfixiantes.",
			"",
			"Resistencia a Poison +30%.",
			"Defensa: 1",
			"Peso: 10",
			"Ubicación: Middle y Lower Head",
		},
		slotCount = 0,
		ClassNum = 91,
	},
	[50828] = {
		unidentifiedDisplayName = "Boots",
		unidentifiedResourceName = "샌들",
		identifiedDisplayName = "Botas de Estabilidad",
		identifiedResourceName = "군용부츠",
		identifiedDescriptionName = {
			"Protegen de Decrease Agi causado por Terreno fangoso.",
			"",
			"Defensa: 5",
			"Peso: 100",
			"Ubicación: Footgear",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50829] = {
		unidentifiedDisplayName = "Robe",
		unidentifiedResourceName = "은혜의성의",
		identifiedDisplayName = "Manto Bendecido",
		identifiedResourceName = "은혜의성의",
		identifiedDescriptionName = {
			"Protege de Curse causado por Tierra maldita.",
			"",
			"MDEF +5. Resistencia a Blind +80%.",
			"Defensa: 45 (Renewal) / 5 (Pre-Renewal)",
			"Peso: 250",
			"Ranura: 1",
			"Ubicación: Garment",
		},
		slotCount = 1,
		ClassNum = 0,
	},
	[50830] = {
		unidentifiedDisplayName = "Mask",
		unidentifiedResourceName = "마스크",
		identifiedDisplayName = "Máscara de Hierba Neutralizante",
		identifiedResourceName = "산소마스크",
		identifiedDescriptionName = {
			"Protege de Sleep causado por Polen somnífero.",
			"",
			"Resistencia a Poison +20%.",
			"Peso: 20",
			"Ubicación: Lower Head",
		},
		slotCount = 0,
		ClassNum = 90,
	},
	[50831] = {
		unidentifiedDisplayName = "Accessory",
		unidentifiedResourceName = "링",
		identifiedDisplayName = "Scriptum Petreum",
		identifiedResourceName = "하이퍼체인저",
		identifiedDescriptionName = {
			"Protege de Stone Curse causado por Hojas Petrificantes.",
			"",
			"HP máximo +50, Defensa +1 en Renewal.",
			"HP máximo +50 en Pre-Renewal.",
			"Peso: 100",
			"Ubicación: Accessory",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50832] = {
		unidentifiedDisplayName = "Hat",
		unidentifiedResourceName = "캡",
		identifiedDisplayName = "Sombrero del Desierto",
		identifiedResourceName = "사막의왕자",
		identifiedDescriptionName = {
			"Protege de Calor intenso y su pérdida extra de sed.",
			"",
			"Indestructible.",
			"Defensa: 3",
			"Peso: 10",
			"Ranura: 1",
			"Ubicación: Upper Head",
		},
		slotCount = 1,
		ClassNum = 567,
	},
	[50833] = {
		unidentifiedDisplayName = "Coat",
		unidentifiedResourceName = "코튼셔츠",
		identifiedDisplayName = "Abrigo Polar",
		identifiedResourceName = "롱코트",
		identifiedDescriptionName = {
			"Protege de Frío extremo y su pérdida extra de hambre.",
			"",
			"Defensa: 42 (Renewal) / 5 (Pre-Renewal)",
			"Peso: 120",
			"Ubicación: Garment",
		},
		slotCount = 0,
		ClassNum = 0,
	},
}
