tbl = {
	[50834] = {
		unidentifiedDisplayName = "Cantimplora",
		unidentifiedResourceName = "canteen_3",
		unidentifiedDescriptionName = { "Una cantimplora." },
		identifiedDisplayName = "Cantimplora (3/3)",
		identifiedResourceName = "canteen_3",
		identifiedDescriptionName = {
			"Una cantimplora de viaje bien sellada.",
			"",
			"Contiene ^0055FF3 sorbos^000000 de agua fresca.",
			"Cada uso recupera ^0055FF10 puntos de sed^000000.",
			"",
			"Peso: ^77777710^000000",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50835] = {
		unidentifiedDisplayName = "Cantimplora",
		unidentifiedResourceName = "이속증가포션",
		unidentifiedDescriptionName = { "Una cantimplora." },
		identifiedDisplayName = "Cantimplora (2/3)",
		identifiedResourceName = "이속증가포션",
		identifiedDescriptionName = {
			"Una cantimplora de viaje.",
			"",
			"Le quedan ^0055FF2 sorbos^000000 de agua.",
			"Cada uso recupera ^0055FF10 puntos de sed^000000.",
			"",
			"Peso: ^7777778^000000",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50836] = {
		unidentifiedDisplayName = "Cantimplora",
		unidentifiedResourceName = "canteen_1",
		unidentifiedDescriptionName = { "Una cantimplora." },
		identifiedDisplayName = "Cantimplora (1/3)",
		identifiedResourceName = "canteen_1",
		identifiedDescriptionName = {
			"Una cantimplora de viaje.",
			"",
			"Le queda ^0055FF1 sorbo^000000 de agua.",
			"Cada uso recupera ^0055FF10 puntos de sed^000000.",
			"",
			"Peso: ^7777776^000000",
		},
		slotCount = 0,
		ClassNum = 0,
	},
	[50837] = {
		unidentifiedDisplayName = "Cantimplora vacía",
		unidentifiedResourceName = "canteen_0",
		unidentifiedDescriptionName = { "Una cantimplora vacía." },
		identifiedDisplayName = "Cantimplora vacía",
		identifiedResourceName = "canteen_0",
		identifiedDescriptionName = {
			"Una cantimplora de viaje vacía.",
			"",
			"No le queda agua.",
			"Úsala cerca de una fuente o cuerpo",
			"de agua para volver a llenarla.",
			"",
			"Peso: ^7777774^000000",
		},
		slotCount = 0,
		ClassNum = 0,
	},
}
